Iter9
nameewgeniy/go-metrics pull request #9
Opened 2023-10-04 16:43 UTC by nameewgeniy

2023-10-05 07:33 UTC, gonozov0 requested changes
Прекрасная работа, очень круто, что уже освоил на практике горутины и каналы, грамотно обрабатываешь ошибки в горутинах 👍
Оставил пару комментариев по улучшению кода

2023-10-05 07:33 UTC, gonozov0 commented on internal/models/metrics_easyjson.go
Скорее всего забыл удалить

2023-10-05 07:33 UTC, gonozov0 commented on internal/models/metrics.go
> +type MetricsFactory struct{}
Круто, что реализовал фабрику, но немного странно, что она находится в пакете models. 

Я бы этот пакет переименовал в metrics, фабрику поместил в отдельный файл, создал пакет shared в internal рядом с agent и server, туда поместил logger и metrics

2023-10-05 07:33 UTC, gonozov0 commented on internal/server/handlers/responsewriter/compress.go
> +package responsewriter
Вроде этот пакет используется только middleware, стоит поместить в middleware/internal

2023-10-05 07:33 UTC, gonozov0 commented on internal/server/server.go
> +	}
У тебя получается чтения данных из файла происходит за пределами основного потока и гипотетически может сложится ситуация, когда сервер уже начнет принимать запросы, а хранилище еще не будет проинициализировано данными из файла. Я бы перенес в основной поток эту логику

2023-10-05 07:33 UTC, gonozov0 commented on cmd/server/main.go
> +	go func() { srv.Listen(errorCh) }()
Можно не делать в рамках этой итерации, но в дальнейшем при спавне каждой горутины важно передавать контекст с возможностью отмены. И когда получили ошибку в канале, то отменять контекст, чтобы все горутины прекратили свою работу и не было утечек памяти

2023-10-05 07:33 UTC, gonozov0 commented on internal/server/storage/storage.go
> +	Snapshot() error
Я бы не расширял интерфейс этими методами, в дальнейшем у нас будет реализация DBStorage, в которых эти методы уже будут лишними. Там где они используются, я бы заложил использование именно MemoryStorage, чтобы не нужно было расширять интерфейс

2023-10-05 19:51 UTC, nameewgeniy commented on internal/models/metrics_easyjson.go
Тут не совсем понял, я использую easyjson, он генерирует реализацию для серелизации и десерелизации структуры

2023-10-05 19:52 UTC, nameewgeniy commented on internal/models/metrics.go
> +type MetricsFactory struct{}
Внёс изменения

2023-10-05 19:52 UTC, nameewgeniy commented on internal/server/server.go
> +	}
Вынес в основной поток

2023-10-05 19:52 UTC, nameewgeniy commented on internal/server/handlers/responsewriter/compress.go
> +package responsewriter
Перенёс реализцию

2023-10-05 19:53 UTC, nameewgeniy commented on cmd/server/main.go
> +	go func() { srv.Listen(errorCh) }()
Изменил реализацию на использование errgroup

2023-10-05 19:54 UTC, nameewgeniy commented on internal/server/storage/storage.go
> +	Snapshot() error
Вынес в отельный интерфейс с реализацией в memory

2023-10-06 06:47 UTC, gonozov0 approved these changes
Все моменты поправлены, апрув 👍

2023-10-06 07:08 UTC, merged